import Head from 'next/head'
import Image from 'next/image'
import Navbar from "../components/Navbar";
import HeroAd from "../components/HeroAd";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
        <HeroAd />
        <div className="hero min-h-screen bg-base-100">
            <div className="hero-content text-center">
                <div className="max-w-lg">
                    <Image src={"/group.png"} width={800} height={500} objectFit={"cover"}/>
                    <h1 className="text-5xl font-bold">Who are we?</h1>
                    <p className="py-6">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi
                        exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
                </div>
            </div>
        </div>
    </div>
  )
}
